### ISSUE TITLE
Generar contenido para la base de datos

### ISSUE THREAD

**Issue by GI-gabriel** [GI-gabriel/cac-24166-grupo-10-be#3]
Generar contenido para la base de datos
Con chatGPT generar textos descriptivos para los campos de la base de datos.
Crear contenido para 10 propiedades, que después vamos a cargar en la base de datos.
Buscar fotos para las 10 propiedades (3 fotos por cada propiedad). Editar para que la foto tenga 810x810px así no rompemos el formato del front-end que ya tenemos.

**Comment by mikeowl** [comment]
Hola Gaby, pienso que para esta tarea se podría llegar a utilizar el módulo Faker de Python
https://faker.readthedocs.io/en/master/
